/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemagerenciadoralimentos;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author Vaio
 */
public class CriarReceita extends javax.swing.JFrame {

    private SistemaGerenciadorAlimentos sistema;

    /**
     * Creates new form CriarReceita
     */
    public CriarReceita(SistemaGerenciadorAlimentos sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblTitulo = new javax.swing.JLabel();
        jlblNomeReceita = new javax.swing.JLabel();
        jlblIngrediente1 = new javax.swing.JLabel();
        jlblingrediente2 = new javax.swing.JLabel();
        jlblIngrediente3 = new javax.swing.JLabel();
        jlblIngrediente4 = new javax.swing.JLabel();
        jlblIngrtediente5 = new javax.swing.JLabel();
        jtfNomeReceita = new javax.swing.JTextField();
        jtfIngrediente1 = new javax.swing.JTextField();
        jtfIngrediente2 = new javax.swing.JTextField();
        jtfIngrediente3 = new javax.swing.JTextField();
        jtfIngrediente4 = new javax.swing.JTextField();
        jtfIngrediente5 = new javax.swing.JTextField();
        jlblQuantidade1 = new javax.swing.JLabel();
        jlblQuantidade2 = new javax.swing.JLabel();
        jlblQuantidade3 = new javax.swing.JLabel();
        jlblQuantidade4 = new javax.swing.JLabel();
        jlblQuantidade5 = new javax.swing.JLabel();
        jtfQuantidade1 = new javax.swing.JTextField();
        jtfQuantidade2 = new javax.swing.JTextField();
        jtfQuantidade3 = new javax.swing.JTextField();
        jtfQuantidade4 = new javax.swing.JTextField();
        jtfQuantidade5 = new javax.swing.JTextField();
        jlblModoPreparo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jbtVoltar = new javax.swing.JButton();
        jbtConcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblTitulo.setText("Crie sua Receita");

        jlblNomeReceita.setText("Nome da Receita:");

        jlblIngrediente1.setText("Ingrediente 1:");

        jlblingrediente2.setText("Ingrediente 2:");

        jlblIngrediente3.setText("Ingrediente 3:");

        jlblIngrediente4.setText("Ingrediente 4:");

        jlblIngrtediente5.setText("Ingrediente 5:");

        jlblQuantidade1.setText("Quantidade:");

        jlblQuantidade2.setText("Quantidade:");

        jlblQuantidade3.setText("Quantidade:");

        jlblQuantidade4.setText("Quantidade:");

        jlblQuantidade5.setText("Quantidade:");

        jlblModoPreparo.setText("Modo de preparo:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jbtVoltar.setText("Voltar");
        jbtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltarActionPerformed(evt);
            }
        });

        jbtConcluir.setText("Concluir");
        jbtConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblTitulo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlblIngrtediente5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblIngrediente4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblIngrediente3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblingrediente2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblIngrediente1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblNomeReceita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfIngrediente1)
                                    .addComponent(jtfIngrediente2)
                                    .addComponent(jtfIngrediente3)
                                    .addComponent(jtfIngrediente4)
                                    .addComponent(jtfIngrediente5, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(jtfNomeReceita))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblQuantidade1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblQuantidade2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblQuantidade3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblQuantidade4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblQuantidade5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfQuantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfQuantidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfQuantidade3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfQuantidade4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfQuantidade5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblModoPreparo)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtConcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jbtVoltar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNomeReceita)
                    .addComponent(jtfNomeReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblIngrediente1)
                    .addComponent(jtfIngrediente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblQuantidade1)
                    .addComponent(jtfQuantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblingrediente2)
                    .addComponent(jtfIngrediente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblQuantidade2)
                    .addComponent(jtfQuantidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblIngrediente3)
                    .addComponent(jtfIngrediente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblQuantidade3)
                    .addComponent(jtfQuantidade3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblIngrediente4)
                    .addComponent(jtfIngrediente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblQuantidade4)
                    .addComponent(jtfQuantidade4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblIngrtediente5)
                    .addComponent(jtfIngrediente5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblQuantidade5)
                    .addComponent(jtfQuantidade5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblModoPreparo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtVoltar)
                    .addComponent(jbtConcluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtVoltarActionPerformed

    private void jbtConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConcluirActionPerformed
        String nomeReceita = jtfNomeReceita.getText().trim();
        String modoPreparo = jTextArea1.getText().trim();

        try {
            // Cria um objeto Receita
            Receita novaReceita = new Receita(0, nomeReceita); // 0 como placeholder para ID
            novaReceita.setModoPreparo(modoPreparo);

            // Coleta os ingredientes e quantidades da interface
            List<JTextField> camposIngredientes = Arrays.asList(jtfIngrediente1, jtfIngrediente2, jtfIngrediente3, jtfIngrediente4, jtfIngrediente5);
            List<JTextField> camposQuantidades = Arrays.asList(jtfQuantidade1, jtfQuantidade2, jtfQuantidade3, jtfQuantidade4, jtfQuantidade5);

            List<Produto> ingredientes = new ArrayList<>();
            List<Integer> quantidades = new ArrayList<>();

            for (int i = 0; i < camposIngredientes.size(); i++) {
                String nomeIngrediente = camposIngredientes.get(i).getText().trim();
                if (!nomeIngrediente.isEmpty()) {
                    Produto produto = sistema.buscarProdutoPorNome(nomeIngrediente);
                    if (produto != null) {
                        ingredientes.add(produto);
                        int quantidade = Integer.parseInt(camposQuantidades.get(i).getText().trim());
                        quantidades.add(quantidade);
                    } else {
                        JOptionPane.showMessageDialog(this, "Produto não encontrado: " + nomeIngrediente, "Erro", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
            }

            // Verifica se a lista de ingredientes não está vazia
            if (!ingredientes.isEmpty()) {
                // Utiliza ReceitaRepositorio para salvar a receita e seus ingredientes na base de dados
                ReceitaRepositorio repo = sistema.getReceitaRepositorio();
                repo.adicionarReceitaComIngredientes(novaReceita, ingredientes, quantidades);

                JOptionPane.showMessageDialog(this, "Receita criada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                this.dispose(); // Fecha a janela atual
            } else {
                JOptionPane.showMessageDialog(this, "Nenhum ingrediente válido fornecido.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar a receita: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtConcluirActionPerformed
//esta parte foi removida

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbtConcluir;
    private javax.swing.JButton jbtVoltar;
    private javax.swing.JLabel jlblIngrediente1;
    private javax.swing.JLabel jlblIngrediente3;
    private javax.swing.JLabel jlblIngrediente4;
    private javax.swing.JLabel jlblIngrtediente5;
    private javax.swing.JLabel jlblModoPreparo;
    private javax.swing.JLabel jlblNomeReceita;
    private javax.swing.JLabel jlblQuantidade1;
    private javax.swing.JLabel jlblQuantidade2;
    private javax.swing.JLabel jlblQuantidade3;
    private javax.swing.JLabel jlblQuantidade4;
    private javax.swing.JLabel jlblQuantidade5;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JLabel jlblingrediente2;
    private javax.swing.JTextField jtfIngrediente1;
    private javax.swing.JTextField jtfIngrediente2;
    private javax.swing.JTextField jtfIngrediente3;
    private javax.swing.JTextField jtfIngrediente4;
    private javax.swing.JTextField jtfIngrediente5;
    private javax.swing.JTextField jtfNomeReceita;
    private javax.swing.JTextField jtfQuantidade1;
    private javax.swing.JTextField jtfQuantidade2;
    private javax.swing.JTextField jtfQuantidade3;
    private javax.swing.JTextField jtfQuantidade4;
    private javax.swing.JTextField jtfQuantidade5;
    // End of variables declaration//GEN-END:variables
}
