/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemagerenciadoralimentos;

import javax.swing.JOptionPane;

/**
 *
 * @author Vaio
 */
public class TabelaNutricionalCadastro extends javax.swing.JFrame {

    private String nomeProduto;

    private SistemaGerenciadorAlimentos sistema;

    /**
     * Creates new form TabelaNutricionalCadastro
     */
    public TabelaNutricionalCadastro(SistemaGerenciadorAlimentos sistema, String nomeProduto) {
        this.sistema = sistema;
        this.nomeProduto = nomeProduto;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblTitulo = new javax.swing.JLabel();
        jlblPorcaoReferencia = new javax.swing.JLabel();
        jlblProteinas = new javax.swing.JLabel();
        jlblCarboidratos = new javax.swing.JLabel();
        jlblCalorias = new javax.swing.JLabel();
        jlblGordurasTotais = new javax.swing.JLabel();
        jtfPorcaoReferencia = new javax.swing.JTextField();
        jtfProteinas = new javax.swing.JTextField();
        jtfCarboidratos = new javax.swing.JTextField();
        jtfCalorias = new javax.swing.JTextField();
        jtfGordurasTotais = new javax.swing.JTextField();
        jbtVoltar = new javax.swing.JButton();
        jbtConcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblTitulo.setText("Cadastro das Informações Nutricionais");

        jlblPorcaoReferencia.setText("Porção Referencia:");

        jlblProteinas.setText("Proteinas:");

        jlblCarboidratos.setText("Carboidratos:");

        jlblCalorias.setText("Calorias:");

        jlblGordurasTotais.setText("Gorduras Totais:");

        jbtVoltar.setText("Voltar");
        jbtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltarActionPerformed(evt);
            }
        });

        jbtConcluir.setText("Concluir");
        jbtConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlblGordurasTotais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblCarboidratos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblProteinas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblPorcaoReferencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblCalorias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfPorcaoReferencia)
                            .addComponent(jtfProteinas)
                            .addComponent(jtfCarboidratos)
                            .addComponent(jtfCalorias)
                            .addComponent(jtfGordurasTotais, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtConcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtVoltar)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlblTitulo)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPorcaoReferencia)
                    .addComponent(jtfPorcaoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblProteinas)
                    .addComponent(jtfProteinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCarboidratos)
                    .addComponent(jtfCarboidratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCalorias)
                    .addComponent(jtfCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblGordurasTotais)
                    .addComponent(jtfGordurasTotais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtVoltar)
                    .addComponent(jbtConcluir))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltarActionPerformed
        CadastrarProduto telaCadastrarProduto = new CadastrarProduto(sistema);
        telaCadastrarProduto.setLocationRelativeTo(null);
        telaCadastrarProduto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtVoltarActionPerformed

    private void jbtConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConcluirActionPerformed
        try {
            double porcaoReferencia = Double.parseDouble(jtfPorcaoReferencia.getText().trim());
            double proteinas = Double.parseDouble(jtfProteinas.getText().trim());
            double carboidratos = Double.parseDouble(jtfCarboidratos.getText().trim());
            double calorias = Double.parseDouble(jtfCalorias.getText().trim());
            double gordurasTotais = Double.parseDouble(jtfGordurasTotais.getText().trim());

            // Buscar o ID do produto usando o nome
            Produto produto = sistema.buscarProdutoPorNome(nomeProduto);
            if (produto == null) {
                JOptionPane.showMessageDialog(this, "Produto não cadastrado. Por favor, cadastre o produto primeiro.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Criar um objeto TabelaNutricionalProduto
            TabelaNutricionalProduto tabelaNutricional = new TabelaNutricionalProduto(
                    porcaoReferencia, proteinas, carboidratos, calorias, gordurasTotais);
            tabelaNutricional.setProdutoId(produto.getId());

            // Salvar a tabela nutricional no banco de dados
            sistema.getTabelaNutricionalProdutoRepositorio().salvarTabelaNutricional(tabelaNutricional);
            JOptionPane.showMessageDialog(this, "Informações nutricionais cadastradas com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Verifique os valores informados e tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtConcluirActionPerformed

    //Esta parte foi removida

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtConcluir;
    private javax.swing.JButton jbtVoltar;
    private javax.swing.JLabel jlblCalorias;
    private javax.swing.JLabel jlblCarboidratos;
    private javax.swing.JLabel jlblGordurasTotais;
    private javax.swing.JLabel jlblPorcaoReferencia;
    private javax.swing.JLabel jlblProteinas;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JTextField jtfCalorias;
    private javax.swing.JTextField jtfCarboidratos;
    private javax.swing.JTextField jtfGordurasTotais;
    private javax.swing.JTextField jtfPorcaoReferencia;
    private javax.swing.JTextField jtfProteinas;
    // End of variables declaration//GEN-END:variables
}
