/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemagerenciadoralimentos;

/**
 *
 * @author Vaio
 */
public class TelaInicial extends javax.swing.JFrame {

    private SistemaGerenciadorAlimentos sistema;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial(SistemaGerenciadorAlimentos sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtCadastrarProduto = new javax.swing.JButton();
        jlblMinhaDispenca = new javax.swing.JLabel();
        jbtCriarReceita = new javax.swing.JButton();
        jbtVisualizarReceita = new javax.swing.JButton();
        jbtProdutosDispenca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jbtCadastrarProduto.setText("Cadastrar Produto");
        jbtCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCadastrarProdutoActionPerformed(evt);
            }
        });

        jlblMinhaDispenca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblMinhaDispenca.setText("Minha Dispença");

        jbtCriarReceita.setText("Criar uma Receita");
        jbtCriarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCriarReceitaActionPerformed(evt);
            }
        });

        jbtVisualizarReceita.setText("Visualizar uma Receita");
        jbtVisualizarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVisualizarReceitaActionPerformed(evt);
            }
        });

        jbtProdutosDispenca.setText("Produtos na Dispença");
        jbtProdutosDispenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtProdutosDispencaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtVisualizarReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtCadastrarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblMinhaDispenca, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtCriarReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtProdutosDispenca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblMinhaDispenca)
                .addGap(51, 51, 51)
                .addComponent(jbtCadastrarProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCriarReceita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtVisualizarReceita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtProdutosDispenca)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCadastrarProdutoActionPerformed
        CadastrarProduto telaCadastrarProduto = new CadastrarProduto(sistema);
        telaCadastrarProduto.setLocationRelativeTo(null);
        telaCadastrarProduto.setVisible(true);
    }//GEN-LAST:event_jbtCadastrarProdutoActionPerformed

    private void jbtCriarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCriarReceitaActionPerformed
        CriarReceita telaCriarReceita = new CriarReceita(sistema);
        telaCriarReceita.setLocationRelativeTo(null);
        telaCriarReceita.setVisible(true);
    }//GEN-LAST:event_jbtCriarReceitaActionPerformed

    private void jbtVisualizarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVisualizarReceitaActionPerformed
        VisualizarReceitas telaVisualizarReceitas = new VisualizarReceitas(sistema);
        telaVisualizarReceitas.setLocationRelativeTo(null);
        telaVisualizarReceitas.setVisible(true);
    }//GEN-LAST:event_jbtVisualizarReceitaActionPerformed

    private void jbtProdutosDispencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtProdutosDispencaActionPerformed
        ProdutoNaDispensa telaProdutoNaDispensa = new ProdutoNaDispensa(sistema);
        telaProdutoNaDispensa.setLocationRelativeTo(null);
        telaProdutoNaDispensa.setVisible(true);
    }//GEN-LAST:event_jbtProdutosDispencaActionPerformed

   //esta parte foi removida
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtCadastrarProduto;
    private javax.swing.JButton jbtCriarReceita;
    private javax.swing.JButton jbtProdutosDispenca;
    private javax.swing.JButton jbtVisualizarReceita;
    private javax.swing.JLabel jlblMinhaDispenca;
    // End of variables declaration//GEN-END:variables
}
